name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps with Bun
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Publish to npm
        run: |
          cd dist/core
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
