name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps with Bun
        run: bun install --frozen-lockfile

      - name: Build project
        run: |
          bun run build core

      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          BASE_DIR=dist
          cd $BASE_DIR/core
          npm publish
          cd $BASE_DIR/express
          npm publish
          cd $BASE_DIR/prisma
          npm publish
          cd $BASE_DIR/ui
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
